Added Unity audio record but still doesn't work
binbat/joyrtc pull request #33
Opened 2023-09-12 12:50 UTC by tulingcheng86

2023-09-12 15:01 UTC, a-wing requested changes
Finally, The Unity need deploy to headless server

The headless server no Microphone!

* * *

We're need capture audio in Browser

After, use webrtc add a audio trick

```
Browser audio stream -> webrtc -> unity
```

Unity receive  the audio stream

Save the audio stream, and replay the audio

2023-09-12 15:01 UTC, a-wing commented on unity/Assets/AudioRecorder.cs
> +    AudioClip recordedClip = Microphone.Start(microphoneDevice, false, maxRecordTime, 44100);
I think unity don't need use Microphone

2023-09-12 15:01 UTC, a-wing commented on unity/Assets/AudioRecorder.cs
> +    BinaryWriter writer = new BinaryWriter(stream);
Maybe there should use audio library

2023-09-12 15:01 UTC, a-wing commented on unity/Assets/CanvasTextSender.cs
> +    ws = new WebSocket("ws://your_websocket_server_address");
We already have a webrtc datachannel and a websocket connection, Why need a new Webcocket?

2023-10-27 11:47 UTC, tulingcheng86 commented on unity/Assets/AudioRecorder.cs
> +    AudioClip recordedClip = Microphone.Start(microphoneDevice, false, maxRecordTime, 44100);
can remove it

2023-10-27 11:48 UTC, merged